name: "Mirror master brach to AUR"
description: "Mirror a repository's master branch to AUR."
branding:
  icon: "archive"
  color: "blue"
inputs:
  ssh_private_key:
    description: "SSH private key for AUR connection"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
